spring:
  application:
    name: Cinema
    domain: http://localhost:8080
  datasource:
    url: jdbc:h2:file:./.h2db/cinema;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092
    username: sa
    password: password
    driverClassName: org.h2.Driver
  mail:
    host: smtp.freesmtpservers.com
    port: 25
    username: username
    password: password
    protocol: smtp
    debug: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 25MB
  h2:
    console:
      path: /console
      settings:
        trace: false
        web-allow-others: false
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  security:
    remember-me:
      secret: c926f25b96c78a9aa954e0ff964d31698da696944e4496464cedb94efa8ab2c0